---
services:
  fluxhaus-server:
    image: ghcr.io/djensenius/fluxhaus-server:latest
    # build: .
    ports:
      - "8080:8080"
    volumes:
      - ./cache:/app/cache
      - .env:/app/.env
    restart: unless-stopped
