---
name: Tag on Merge

"on":
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Create Tag
        run: |
          VERSION=${{ github.event.pull_request.head.ref }}
          VERSION=${VERSION#release/}
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
